version: '3.8'

services:
  webapp:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: simplewebapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=SimpleWebAppDb;user=root;password=root
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SimpleWebAppDb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
